# Generated by Django 4.0 on 2022-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_account_created_by_alter_account_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
